name: growth_agent
model: gpt-4o-mini

steps:
  - brief_parser
  - if: "{{ENV['DEMO_MODE'] == 'true'}}"
    then:
      - mock_notion_profiles_getter
    else:
      - notion_profiles_getter
  - profile_filter_prompt
  - profile_filter_parser
  - if: "{{ENV['DEMO_MODE'] == 'true'}}"
    then:
      - mock_bios_fetcher
    else:
      - bios_fetcher
  - pod_generator_prompt
  - pod_generator
  - output_generator

profile_filter_prompt:
  print_response: false
  json: true

pod_generator_prompt:
  print_response: false
  json: true
