require "roast"
require "bundler/setup"
require "roast/workflow/base_step"
require "roast/workflow/prompt_step"
require "roast/workflow/base_iteration_step"
require "roast/workflow/repeat_step"
require "roast/workflow/each_step"
require "roast/workflow/base_workflow"
require "roast/workflow/configuration"
require "roast/workflow/workflow_execution_context"
require "roast/workflow/workflow_executor"
require "roast/workflow/configuration_parser"
require "roast/workflow/validator"
require "roast/workflow/state_repository"
require "roast/workflow/session_manager"
require "roast/workflow/file_state_repository"
class WorkflowTest
  include Roast::Workflow
end
